language: cpp

sudo: false
cache: ccache

compiler:
  - gcc  
  - clang

# gcc 4.9 default
addons: &addons
  apt:
    packages: &packages
      - g++-4.9
      - libboost-test-dev
      - libboost-system-dev
      - libcurl4-openssl-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5

env:
  global:
    - TELEBOTXX_BUILD_TESTS=ON
    - TELEBOTXX_GENERATE_DOC=OFF
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9

matrix:
  include:
    # gcc 4.9
    - env: COMPILER=g++-4.9 CCOMPILER=gcc-4.9
      addons:
        apt:
          packages: g++-4.9
          sources: *sources

    # Clang 3.5
    - env: COMPILER=clang++-3.5 CCOMPILER=clang-3.5
      addons:
        apt:
          packages: clang-3.5
          sources: *sources

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - ./configure

script:
  - make -j2 VERBOSE=1
