
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

env:
  global:
    - TELEBOTXX_BUILD_TESTS=ON
    - TELEBOTXX_GENERATE_DOC=OFF

before_script:
  - sudo apt-get install -y libboost-test-dev libboost-system-dev libcurl4-openssl-dev
  - export CXX=$COMPILER
  - mkdir build
  - cd build
  - cmake ..

script:
  - make VERBOSE=1
