language: cpp

sudo: false
cache: ccache

compiler:
  - gcc  
  - clang

# gcc 4.9 default
addons: &addons
  apt:
    packages: &packages
      - g++-4.9
      - clang-format-3.7
      - python-pip
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8

env:
  global:
    - TELEBOTXX_BUILD_TESTS=ON
    - TELEBOTXX_GENERATE_DOC=OFF
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9

matrix:
  include:
    # Clang 3.7
    - env: COMPILER=clang++-3.7 CCOMPILER=clang-3.7
      addons:
        apt:
          packages: clang-3.7
          sources: *sources

before_script:
  - ./configure

script:
  - make -j2 VERBOSE=1
