sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:kzemek/boost'
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:kzemek/boost'
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6

env:
  global:
    - TELEBOTXX_BUILD_TESTS=ON
    - TELEBOTXX_GENERATE_DOC=OFF

before_script:
  - sudo apt-get install -y libboost1.58-dev libboost-test1.58-dev libboost-system1.58-dev libcurl4-openssl-dev
  - export CXX=$COMPILER
  - mkdir build
  - cd build
  - cmake ..

script:
  - make VERBOSE=1
